spring:
  # Disable the default auto-configuration for Redis since we are including the auto-configuration for Redis Vector Store.
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  main:
    web-application-type: none
  application:
      name: temporal-spring-ai-chat
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          # Any model supported by Spring AI can be used here. It will be autowired into the ChatModelActivity.
          model: gpt-4o
          temperature: 0.7
  temporal:
    namespace: ${TEMPORAL_NAMESPACE}
    connection:
      target: ${TEMPORAL_ADDRESS}
      api-key: ${TEMPORAL_API_KEY}
    workflow-cache:
      using-virtual-workflow-threads: true
    workers:
      - task-queue: temporal-spring-ai-chat-taskqueue
        workflow-classes:
          - io.temporal.ai.workflows.ChatWorkflowImpl
        activity-beans:
          - chatModelActivity
          - dateTimeToolsImpl
---
spring:
  autoconfigure:
    exclude:
  config:
    activate:
      on-profile: vectorstore-redis
  data:
    redis:
      host: localhost
      password: "mypassword"
      username: "default"
  ai:
    vectorstore:
      redis:
        initialize-schema: true
  temporal:
    workers:
      - task-queue: temporal-spring-ai-chat-taskqueue
        activity-beans:
          - chatModelActivity
          - dateTimeToolsImpl
          - vectorStoreActivity